# [Info]
site_name: 李若诗的个人网站 Ruoshi LI's personal website
site_url: https://ruoshi93.github.io
site_author: 李若诗 Ruoshi LI
site_description: 李若诗的个人网站 Ruoshi LI's personal website

# [Navigtion]
nav:
  - 博客:
    - blog/index.md
    - 数据库的使用与实现:
      - blog/ERDB/1_Transactions.md
      - blog/ERDB/2_Recovery.md


# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: light blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: switch to dark mode # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: switch to light mode
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: en # 一些提示性的文字会变成英文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/ruoshi93/ruoshi93.github.io # 右上角点击跳转的链接
repo_name: ruoshi93.github.io # 右上角的名字
## [bottom-left corner]
copyright: 李若诗 Ruoshi LI CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/ruoshi93
      name: GitHub | ruoshi93
  alternate:
    - name: English
      link: /docs/blog/ERDB
      lang: en
    - name: Deutsch
      link: /de/
      lang: de